name: Commit Reports

description: Commit generated reports to the ci-reports branch

inputs:

  report-type:
    description: Type de rapport (python, rust, security...)
    required: false
    

  commit-message:
    description: Message du commit
    required: true

  branch:
    description: Branche de destination
    required: false
    default: ci-reports

runs:
  using: composite

  steps:

    - shell: bash
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git status

    - shell: bash
      run: |
            git fetch origin
            if git show-ref --verify --quiet refs/remotes/origin/${{ inputs.branch }}
            then
            git ls-tree -r --name-only origin/${{ inputs.branch }} | wc -l
            
            git worktree add /tmp/ci-worktree origin/${{ inputs.branch }}
            else
            git worktree add -b ${{ inputs.branch }} /tmp/ci-worktree
            fi
            mkdir -p "/tmp/ci-worktree/reports/${{ inputs.report-type }}"
            mkdir -p "/tmp/ci-worktree/database/
            cp -r reports/. "/tmp/ci-worktree/reports/${{ inputs.report-type }}/" 2>/dev/null || true
            cp -r database/. "/tmp/ci-worktree/database/" 2>/dev/null || true
            cd /tmp/ci-worktree
            git add .
            git status
            if git diff --cached --quiet; then
            echo "No changes to commit."
            cd -
            git worktree remove /tmp/ci-worktree --force
            exit 0
            fi
            git commit -m "${{ inputs.commit-message }}"
            for i in 1 2 3
            do
            git fetch origin ci-reports
            git rebase origin/ci-reports
            if git push origin HEAD:${{ inputs.branch }}
            then
            echo "Push réussi"
            cd -
            git worktree remove /tmp/ci-worktree --force
            exit 0
            fi
            echo "Nouvelle tentative..."
            sleep 2
            done
            cd "$GITHUB_WORKSPACE"
            git worktree remove /tmp/ci-worktree --force
            exit 1
           
