[package]
name = "the-last-signal-server"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
rand = "0.8" 
serde_json = "1.0"
aes-gcm = "0.10.1"
pbkdf2 = { version = "0.12", features = ["simple"] }
sha2 = "0.10"
# Pour l'encodage/décodage Base64
base64 = "0.21"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }


# Pour la gestion des fichiers ZIP
zip = "0.6"

# Pour la gestion des dates (équivalent à `datetime` en Python)
chrono = "0.4"

# Pour la normalisation des chaînes (équivalent à `unicodedata.normalize`)
unicode-normalization = "0.1"

# Pour la création de fichiers temporaires
tempfile = "3.3"
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "postgres",
    "uuid",
    "chrono"
] }

tokio = { version = "1", features = ["full"] }
anyhow = "1"
