name: Generate Vault Key

on:
  workflow_dispatch:

jobs:
  generate:

    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@
        - name: Setup Python
          uses: actions/setup-python@v5
          with:
             python-version: "3.14"
             cache: "pip"
        - name: Install dependencies
          run: |

                  python -m pip install --upgrade pip setuptools wheel
                  if [ -f requirements.txt ]; then
                  pip install -r requirements.txt
                  fi
          

        - name: Generate key
          run: |
                 python3 - <<EOF
                 from cryptography.fernet import Fernet

                 key = Fernet.generate_key()

                 print(key.decode())
                 EOF
