name: launcher

on:
  push:
    branches:
      - main
  
    

  workflow_dispatch:
  workflow_call:

  schedule:
    - cron: "15 * * * *"
concurrency:
  group: main-update
  queue: max
permissions:
  actions: write
  contents: write
  security-events: write
  pull-requests: write

jobs:
  
  integration:
    
    
    uses: ./.github/workflows/integration.yml
    secrets:
        VAULT_KEY: ${{ secrets.VAULT_KEY }}
    
  python:
    needs: integration
    if: >-
     ${{
      always() &&
      (
        needs.integration.result == 'success' ||
        needs.integration.result == 'failure'
      )
     }}
    uses: ./.github/workflows/python.yml

  rust:
    needs: python
    if: >-
     ${{
      always() &&
      (
        needs.python.result == 'success' ||
        needs.python.result == 'failure'
      )
     }}
    uses: ./.github/workflows/rust.yml

  build:
    needs: rust
    if: >-
     ${{
      always() &&
      (
        needs.rust.result == 'success' ||
        needs.rust.result == 'failure'
      )
     }}
    uses: ./.github/workflows/build.yml

  


  
  project:
    needs: build
    if: >-
     ${{
      always() &&
      (
        needs.build.result == 'success' ||
        needs.build.result == 'failure'
      )
     }}
    uses: ./.github/workflows/project.yml
  
  
 

  sync:
    needs: project
    if: >-
     ${{
      always() &&
      (
        needs.project.result == 'success' ||
        needs.project.result == 'failure'
      )
     }}
    uses: ./.github/workflows/sync-ci.yml
  cancel-launcher:
    needs:

      - integration
      - python
      - rust
      - project
      - sync
    if: >-
     ${{
      always() &&
      (
        needs.reset.result == 'failure' ||
        needs.integration.result == 'failure' ||
        needs.python.result == 'failure' ||
        needs.rust.result == 'failure' ||
        needs.project.result == 'failure' ||
        needs.sync.result == 'failure'
      )
     }}
    uses: ./.github/workflows/cancel-pending.yml
    with: 
      mode: launcher
  
