name: Nightly

on:
  workflow_dispatch:

  schedule:
    - cron: "0 22 * * *"
concurrency:
  group: nighly
  queue: max

permissions:
  actions: write
  contents: write
  security-events: write
  pull-requests: write

jobs:

  launch:
    uses: ./.github/workflows/Launcher.yml
  build:
    needs: launch
    if: >-
     ${{
      always() &&
      (
        needs.launch.result == 'success' ||
        needs.launch.result == 'failure'
      )
     }}
    uses: ./.github/workflows/build.yml
  archive:
    needs: build
    if: >-
     ${{
      always() &&
      (
        needs.build.result == 'success' ||
        needs.build.result == 'failure'
      )
     }}
    uses: ./.github/workflows/Archive.yml

  

  security:
    needs: archive
    if: >-
     ${{
      always() &&
      (
        needs.archive.result == 'success' ||
        needs.archive.result == 'failure'
      )
     }}
    
    uses: ./.github/workflows/security.yml
    secrets:
        VAULT_KEY: ${{ secrets.VAULT_KEY }}

  cancel-nightly:
    needs:
      - launch
      - build
      - archive
      - security
      
    if: >-
     ${{
      always() &&
      (
        needs.launch.result == 'failure' ||
        needs.build.result == 'failure' ||
        needs.archive.result == 'failure' ||
        needs.security.result == 'failure' 
      )
     }}
    uses: ./.github/workflows/cancel-pending.yml
    with: 
      mode: nighly

  

  
  
