name: Nightly

on:
  workflow_dispatch:

  schedule:
    - cron: "0 22 * * *"

permissions:
  actions: write
  contents: write
  security-events: write

jobs:

  launch:
    uses: ./.github/workflows/Launcher.yml

  

  security:
    needs: launch
    uses: ./.github/workflows/security.yml

  

  sync:
    needs: security
    uses: ./.github/workflows/sync-ci.yml
  
