name: Add Secret To Vault

on:
  workflow_dispatch:

    inputs:

      name:
        description: "Nom du secret"
        required: true

      value:
        description: "Valeur du secret"
        required: true


permissions:
  contents: write


jobs:

  add-secret:

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
             python-version: "3.14"
             cache: "pip"
      - name: Install dependencies
        run: |

                  python -m pip install --upgrade pip setuptools wheel
                  if [ -f requirements.txt ]; then
                  pip install -r requirements.txt
                  fi


      


      - name: Add secret to vault
        env:
          VAULT_KEY: ${{ secrets.VAULT_KEY }}

        run: |

          python security/vault.py \
          --name "${{ github.event.inputs.name }}" \
          --value "${{ github.event.inputs.value }}"


      - name: Commit vault update
        run: |

          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A security/vault.enc

          git commit -m "Update encrypted vault" || echo "No changes"
          git pull --rebase origin main
          git push
