name: Add Secret To Vault

on:

  workflow_dispatch:

    inputs:

      name:
        description: "Nom du secret"
        required: true

      value:
        description: "Valeur"
        required: true


jobs:

  add:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - name: Install dependencies
        run: |
          pip install cryptography


      - name: Add secret
        env:
          VAULT_KEY: ${{ secrets.VAULT_KEY }}

        run: |

          python security/vault.py \
          --name "${{ github.event.inputs.name }}" \
          --value "${{ github.event.inputs.value }}"


      - name: Save vault

        uses: actions/upload-artifact@v4

        with:

          name: vault

          path: security/vault.enc
