name: Add Secret To Vault

on:

  workflow_dispatch:

    inputs:

      name:
        description: "Nom du secret"
        required: true

      value:
        description: "Valeur"
        required: true


jobs:

  add:

    runs-on: ubuntu-latest

    steps:

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"
          cache: "pip"


      # Installation des outils
      - name: Install dependencies
        run: |

          python -m pip install --upgrade pip setuptools wheel

          

          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          

      

      - name: Add secret
        env:
          VAULT_KEY: ${{ secrets.VAULT_KEY }}

        run: |

          python security/vault.py \
          --name "${{ github.event.inputs.name }}" \
          --value "${{ github.event.inputs.value }}"


      - name: Save vault

        uses: actions/upload-artifact@v4

        with:

          name: vault

          path: security/vault.enc
