name: Reset ci-reports

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  reset:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: reset
        shell: bash
        run: |
               git config --global user.name "github-actions"
               git config --global user.email "github-actions@github.com"
               git fetch origin
               git switch --orphan ci-reports-temp

               git rm -rf . || true
               find . -maxdepth 1 ! -name ".git" ! -name "." -exec rm -rf {} +
               echo "Reports branch" > .gitkeep
               git add .gitkeep
               git commit -m "Initialize empty ci-reports branch"
               git branch -M ci-reports
               git push --force origin ci-reports
