name: Rust CI Report

on:
  push:
    branches:
      - "**"

  pull_request:
    branches:
      - "**"

  workflow_dispatch:

  schedule:
    - cron: "7 * * * *"

permissions:
  contents: write
env:
  RUST_PROJECT: server_rust
jobs:
  rust-report:

    name: Rust Quality Report

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Create report
        run: |
          mkdir -p reports

          REPORT="reports/rust-report-${GITHUB_RUN_NUMBER}.md"

          echo "REPORT=$REPORT" >> $GITHUB_ENV

          {
            echo "# Rust Report"
            echo ""
            echo "Run : ${GITHUB_RUN_NUMBER}"
            echo "Branch : ${GITHUB_REF_NAME}"
            echo "Commit : ${GITHUB_SHA}"
            echo "Date : $(date)"
            echo ""
          } > "$REPORT"

      - name: Cargo fmt
        continue-on-error: true
        run: |
          {
            echo ""
            echo "## Cargo fmt"
          } >> "$REPORT"

          if find . -name Cargo.toml | grep -q .; then
            cargo fmt \
            --manifest-path "$RUST_PROJECT/Cargo.toml"
            >> "$REPORT" 2>&1
          else
            echo "No Rust project found." >> "$REPORT"
          fi

      - name: Cargo clippy
        continue-on-error: true
        run: |
          {
            echo ""
            echo "## Cargo clippy"
          } >> "$REPORT"

          if find . -name Cargo.toml | grep -q .; then
            cargo clippy \
            --manifest-path "$RUST_PROJECT/Cargo.toml" \
            --all-targets \
            --all-features
            >> "$REPORT" 2>&1
          else
            echo "No Rust project found." >> "$REPORT"
          fi

      - name: Cargo test
        continue-on-error: true
        run: |
          {
            echo ""
            echo "## Cargo test"
          } >> "$REPORT"

          if find . -name Cargo.toml | grep -q .; then
            cargo test \
           --manifest-path "$RUST_PROJECT/Cargo.toml" >> "$REPORT" 2>&1
          else
            echo "No Rust tests found." >> "$REPORT"
          fi

      - name: Publish Summary
        run: cat "$REPORT" >> $GITHUB_STEP_SUMMARY

      - name: Commit reports
        uses: ./.github/actions/commit-reports
        with:
          report-type: rust
          commit-message: "Rust Report #${{ github.run_number }}"
